# Generated by Django 3.1 on 2020-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default=0, upload_to='media/images'),
            preserve_default=False,
        ),
    ]
