# Generated by Django 3.1 on 2020-09-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0003_auto_20200918_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cname_desc', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.FloatField(max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='product_cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ekart.category'),
            preserve_default=False,
        ),
    ]
